collections:
  bins:
    output: true

defaults:
  - scope:
      path: ""
      type: "bins"
    values:
      layout: "bin"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

